CREATE TABLE `pool_user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `device_code_bind` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '绑定账号后id的存放处',
  `device_code` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '绑定的设备id',
  `final_device_code` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '设备id',
  `idfa` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `name` VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '姓名',
  `stage` INT(11) NOT NULL DEFAULT '0',
  `trophy` INT(11) NOT NULL DEFAULT '0' COMMENT '杯数',
  `league_level` INT(11) NOT NULL DEFAULT '1' COMMENT '联赛等级',
  `created_time` INT(10) NOT NULL DEFAULT '0' COMMENT '记录写入时间',
  `login_time` INT(11) NOT NULL DEFAULT '0' COMMENT '最后登录时间',
  `logout_time` INT(10) NOT NULL DEFAULT '0' COMMENT '最后登出时间',
  `update_time` INT(11) NOT NULL COMMENT '更改时间',
  `time_diff` TINYINT(3) NOT NULL DEFAULT '0' COMMENT 'UTC时差',
  `has_bind` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已绑定账号',
  `email` VARCHAR(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '邮箱地址',
  `fb_email` VARCHAR(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'fbEmail',
  `facebook_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '绑定的FacebookId',
  `avatar_url` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '头像地址',
  `apple_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'appleId',
  `apple_email` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'apple账户的email',
  `country_code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '国家',
  `lang_code` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '语言',
  `package_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `fcm_token` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'FCM token',
  `user_from` VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '来源',
  `diamond` INT(11) NOT NULL DEFAULT '0' COMMENT '钻石',
  `coin` INT(11) NOT NULL DEFAULT '0' COMMENT '金币',
  `ore` INT(11) NOT NULL DEFAULT '0' COMMENT '资产的一种',
  `token_num` MEDIUMINT(9) NOT NULL DEFAULT '0' COMMENT '体力token',
  `token_update_time` INT(11) NOT NULL DEFAULT '0' COMMENT '体力刷新时间',
  `os_type` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '0:android 1:ios',
  `token` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '服务端token',
  `version_code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `elo` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`) USING BTREE,
  KEY `facebook_id_index` (`facebook_id`) USING BTREE,
  KEY `device_id_idx` (`device_code`) USING BTREE,
  KEY `email_idx` (`email`) USING BTREE,
  KEY `name_idx` (`name`) USING BTREE,
  KEY `token_idx` (`token`) USING BTREE,
  KEY `timdif_idx` (`time_diff`) USING BTREE,
  KEY `fcm_idx` (`fcm_token`) USING BTREE,
  KEY `apple_idx` (`apple_id`) USING BTREE,
  KEY `fd_id_idx` (`final_device_code`) USING BTREE,
  KEY `idfa_idx` (`idfa`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='用户信息表'
